package com.paulo.android.printloglibrary

import java.lang.StringBuilder

open class Samples {
    private var list: ArrayList<String> = ArrayList()
    private var map: HashMap<String, Any> = HashMap()

    fun sample1() {
        val p = PrintLog(true, "SAMPLE - p.help() blueprint")
        p.header()
        val builder = StringBuilder()
        builder.appendLine("# val p = PrintLog(true, 'HELP')")
        builder.appendLine("# p.header()")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log(' {{::SETUP::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('val p = PrintLog(print, title)')")
        builder.appendLine("# p.log('[print] -> print or not the entire block')")
        builder.appendLine("# p.log('[title] -> method or class name')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('val p = PrintLog(print, title, maxLengthBlock)')")
        builder.appendLine("# p.log('[maxLengthBlock] -> block size. Default = 100')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.divider()")
        builder.appendLine("# p.log(' {{::HEADER::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('p.header() is used to create the header block')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.divider()")
        builder.appendLine("# p.log(' {{::FOOTER::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('p.footer() is used to create the footer block')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.divider()")
        builder.appendLine("# p.log(' {{::LOGGERS::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('There are 3 types of loggers:')")
        builder.appendLine("# p.log('p.log(String)')")
        builder.appendLine("# p.log('p.log(String,Any)')")
        builder.appendLine("# p.log('p.log(Any)')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.divider()")
        builder.appendLine("# p.log(' {{::EXTRAS::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('p.divider(), e.g.: #==========#')")
        builder.appendLine("# p.log('p.separator(), e.g.: #----------#')")
        builder.appendLine("# p.log('p.breakLine(), just break a new line')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.divider()")
        builder.appendLine("# p.log(' {{::EXAMPLES::}} ')")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('NULL value:')")
        builder.appendLine("# p.log('p.log(value, null) preview:')")
        builder.appendLine("# p.log('value',null)")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('EMPTY value:')")
        builder.appendLine("# p.log('p.log(value, '') preview:')")
        builder.appendLine("# p.log('value','')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('ArrayList<String> with 4 items:')")
        builder.appendLine("# p.log('p.log(list) preview:')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.log('list',getPopulatedList())")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.separator()")
        builder.appendLine("# p.log('HashMap<String, Any> with 3 keyValues pairs:')")
        builder.appendLine("# p.log('p.log(map) preview:')")
        builder.appendLine("# p.breakLine()")
        builder.appendLine("# p.log('map',getPopulatedMap())")
        builder.appendLine("# p.footer()")
        println(builder.trim())
        p.footer()
    }

    fun help() {
        val p = PrintLog(true, "HELP")
        p.header()
        p.breakLine()
        println("# This sample explains how to use the PrintLog structure.")
        println("# How to assemble the header and footer blocks and how to use the loggers.")
        println("# If you want to see how the help structure was assembled, call p.sample1()")
        p.breakLine()
        p.separator()
        p.log(" {{::SETUP::}} ")
        p.separator()
        p.log("val p = PrintLog(print, title)")
        p.log("[print] -> print or not the entire block")
        p.log("[title] -> method or class name")
        p.separator()
        p.log("val p = PrintLog(print, title, maxLengthBlock)")
        p.log("[maxLengthBlock] -> block size. Default = 100")
        p.breakLine()
        p.divider()
        p.log(" {{::HEADER::}} ")
        p.separator()
        p.log("p.header() is used to create the header block")
        p.breakLine()
        p.divider()
        p.log(" {{::FOOTER::}} ")
        p.separator()
        p.log("p.footer() is used to create the footer block")
        p.breakLine()
        p.divider()
        p.log(" {{::LOGGERS::}} ")
        p.separator()
        p.log("There are 3 types of loggers:")
        p.log("p.log(String)")
        p.log("p.log(String,Any)")
        p.log("p.log(Any)")
        p.breakLine()
        p.divider()
        p.log(" {{::EXTRAS::}} ")
        p.separator()
        p.log("p.divider(), e.g.: #==========#")
        p.log("p.separator(), e.g.: #----------#")
        p.log("p.breakLine(), just break a new line")
        p.breakLine()
        p.divider()
        p.log(" {{::EXAMPLES::}} ")
        p.separator()
        p.log("NULL value:")
        p.log("p.log(value, null) preview:")
        p.log("value",null)
        p.breakLine()
        p.separator()
        p.log("EMPTY value:")
        p.log("p.log(value, '') preview:")
        p.log("value","")
        p.breakLine()
        p.separator()
        p.log("ArrayList<String> with 4 items:")
        p.log("p.log(list) preview:")
        p.breakLine()
        p.log("list",getPopulatedList())
        p.breakLine()
        p.separator()
        p.log("HashMap<String, Any> with 3 keyValues pairs:")
        p.log("p.log(map) preview:")
        p.breakLine()
        p.log("map",getPopulatedMap())
        p.footer()
    }

    private fun getPopulatedList(): ArrayList<String> {
        list.add("First item of the list")
        list.add("Second item of the list")
        list.add("Third item of the list")
        list.add("etc")
        return list
    }

    private fun getPopulatedMap(): HashMap<String, Any> {
        map["key_1"] = 10
        map["key_2"] = "s02"
        map["key_3"] = 0.1f
        return map
    }
}