package com.paulo.android.printloglibrary.constants

object PrintLogConstants {
    internal const val LOG = "LOG"
    internal const val HASHTAG = "#"
    internal const val OPEN_KEYS = "["
    internal const val CLOSE_KEYS = "]"
    internal const val OPEN_PARENTHESIS = "("
    internal const val CLOSE_PARENTHESIS = ")"
    internal const val OPEN_BRACKETS = "{"
    internal const val CLOSE_BRACKETS = "}"
    internal const val CURSOR = "->"
    internal const val POINTER = "=>"
    internal const val BLANK_SPACE = " "
    internal const val LINE = "line"
    internal const val ZERO = "0"
    internal const val ELAPSED_TIME = "Elapsed time:"
    internal const val DAYS = "days:"
    internal const val HOURS = "h:"
    internal const val MINUTES = "m:"
    internal const val SECONDS = "s"
    internal const val AND = "&"
    internal const val BASE = "||"
    internal const val BASE_1 = "|"
    internal const val BASE_2 = "/"
    internal const val BASE_3 = "="
    internal const val BASE_4 = "-"
    internal const val UNDER = "_"
    internal const val INIT = "INIT"
    internal const val END = "END"
    internal const val DOT = "."
    internal const val BALL = "*"
    internal const val DOUBLE_DOTS = ":"
    internal const val SEMICOLON = ";"
    internal const val BREAKLINE = "\n"
    internal const val NULL = "[NULL]"
    internal const val EMPTY = "[EMPTY]"
    internal const val FULL_DATA_FORMAT = "dd/MM/yyyy HH:mm:ss"
    internal const val SHORT_DATA_FORMAT = "dd/MM/yyyy"
    internal const val INDEX = "index"
    internal const val KEY = "key & value: "
    internal const val BASE_START = "start"
    internal const val BASE_END = "end"
    internal const val HEADER = "header"
    internal const val FOOTER = "footer"
    internal const val DIVIDER = "divider"
    internal const val SEPARATOR = "separator"
    internal const val JUMP_LINE = "jumpLine"
    internal const val ONLY_MSG = "onlyMessage"
    internal const val ONLY_VAL = "onlyValue"
    internal const val BOTH_MSG_VAL = "bothMessageAndValue"
    internal const val NOTHING = "[nothing]"
}